- defaults:
    link:
      create: true
      relink: true

- link:
    ~/.config/doom: editors/doom

- shell:
    - 
      command: git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs
      description: Clone doom-emacs
      stderr: true
    
    - 
      command: ~/.config/emacs/bin/doom install --fonts --force
      description: Install doom-emacs
      stdout: true
      stderr: true
