# Set keyboard for work laptop
input "1:1:AT_Translated_Set_2_keyboard" {
  xkb_layout br
}

# Touchpad for work laptop
input "1267:12811:ELAN0683:00_04F3:320B_Touchpad" {
  dwt enabled
  tap enabled
  middle_emulation enabled
}

# Desktop keyboard
input "1133:50504:Logitech_USB_Receiver" {
  xkb_layout br
}
